---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: my-client-406-

resources:
- ../../base

configMapGenerator:
- name: my-configmap
  namespace: default
  behavior: create
  literals:
  - APP_URL=https://my-client-406.example.com
  - SOME=thing

